#!/usr/bin/env python

from pytube import YouTube
from pytube.cli import on_progress
import sys
import os

if len(sys.argv) < 2:
  print("Enter a youtube video url!")
  sys.exit(0)

url = sys.argv[1]
yt = YouTube(url, on_progress_callback=on_progress)

audio = yt.streams.filter(only_audio=True).first()
filename = audio.download(output_path="/home/bl4ck/Music")
base, ext = os.path.splitext(filename)
os.rename(filename, base + ".mp3")
